# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11c6f4027fa4619c20e99891e54467ff899c414bab8f430b0bc0c95266fbd4f2d66d23f737e47564e2f794b78cf5b150dd01eb0c6152f6fe167de1b6e2425607

test:
  secret_key_base: 63f02ddbd552a002db37c5a6f999def1d5b3e2ee83d0edcae14fd873fe3bd44691bcba06323511633ecaa85ebdd1039a6e95cef67f7cb501e4ed0e60b7c4d317

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
